export const shittyStars = [
    {
      id: 1,
      name: "Vincent Lagaffe",
      bio: "Le jet ski c'est mon dada",
      img: "https://file1.telestar.fr/var/telestar/storage/images/2015/photos/vincent-lagaf-decroche-un-record-du-monde-grace-au-flyboard-!-photos-132229/989014-1-fre-FR/Vincent-Lagaf-decroche-un-record-du-monde-grace-au-Flyboard-!-Photos.jpg?alias=original",
      publishedAt: "2020-10-10",
      isPickedByTeam: true,
    },
    {
      id: 2,
      name: "Justin Bieber",
      bio: "hahahahahcedfplêd",
      img: "https://media.gqmagazine.fr/photos/640b1aa5bd6f5c8e911df9ea/master/pass/010322_JBHair_01.jpg",
      publishedAt: "2021-10-10",
      isPickedByTeam: true,
    },
    {
      id: 3,
      name: "Cyril Hanouna",
      bio: "Balance ton post !",
      img: "https://www.letribunaldunet.fr/wp-content/uploads/2023/01/cyril-hanouna-762x476.jpg.webp",
      publishedAt: "2023-10-10",
      isPickedByTeam: true,
    },
    {
      id: 4,
      name: "Kim Kardashian",
      bio: "Life in plastic, it's fantastic",
      img: "https://i.abcnewsfe.com/a/90e6a4aa-154b-41a4-975d-e883016d81e0/kim-kardashian-4-gty-bb-231117_1700233842359_hpEmbed_11x16.jpg",
      publishedAt: "2021-10-13",
      isPickedByTeam: false,
    },
    {
      id: 5,
      name: "Nabilla",
      bio: "Allo, quoi !",
      img: "https://www.bibamagazine.fr/wp-content/uploads/biba/2023/01/nabilla-750x394.jpg",
      publishedAt: "2020-08-25",
      isPickedByTeam: true,
    },
    {
        id: 6,
        name: "Eric Zemmour",
        bio: "La France n'est plus chez elle",
        img: "https://www.bibamagazine.fr/wp-content/uploads/biba/2023/01/zemmour-750x394.jpg",
        publishedAt: "2023-02-06",
        isPickedByTeam: false,
    },
    {
        id: 7,
        name: "Enora Malagré",
        bio: "C'est pas parce qu'on est blonde qu'on est une gourde",
        img: "https://resize.programme-television.org/original/var/premiere/storage/images/news/tv/emissions-tele/enora-malagre-l-inaction-de-la-justice-face-aux-feminicides-me-fait-vomir-4715512/101904543-1-fre-FR/Enora-Malagre-L-inaction-de-la-justice-face-aux-feminicides-me-fait-vomir.jpg",
        publishedAt: "2022-11-31",
        isPickedByTeam: false,
    },
    {
        id: 8,
        name: "Emmanuel Macron",
        bio: "Je ne céderai rien aux fainéants",
        img: "https://www.letribunaldunet.fr/wp-content/uploads/2023/01/emmanuel-macron-1-762x430.jpg.webp",
        publishedAt: "2020-06-24",
        isPickedByTeam: true,
    },
    {
        id: 9,
        name: "Kev Adams",
        bio: "Voilà, c'est fini !",
        img: "https://pbs.twimg.com/profile_images/1646905938585034753/OhyYUASM_400x400.jpg",
        publishedAt: "2022-03-16",
        isPickedByTeam: false,
    },
    {
        id: 10,
        name: "Kany West",
        bio: "I'm not a businessman; I'm a business, man!",
        img: "https://m1.quebecormedia.com/emp/emp/z_GettyImages_1205196725cf006353-eabf-40ee-af28-744a435c107e_ORIGINAL.jpg?impolicy=crop-resize&x=0&y=0&w=2100&h=1181&width=925",
        publishedAt: "2021-10-09",
        isPickedByTeam: true,
    },
  ];

// Je stocke la variable que je vais appeler dans les pages dont j'ai besoin